import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className={styles.main}>
        <section className={styles.aboutSection}>
          <h2 className={styles.sectionHeading}>About us</h2>
          <div className={styles.aboutFlex}>
            <div className={styles.imageCtn}>
              <img src="./about-us.png" alt=""  />
            </div>
            <div>
              <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
              </p>
            </div>
          </div>

          <div >
            <h2 className={styles.sectionHeading} >Lorem ipsum</h2>
            <p className={styles.sectionText}>Lorem Ipsum is simply dummy text of the printing </p>

            <div className={styles.cardsCtn}>
              <div>
                <div className={styles.card}>
                  <img src="./grammer-check.png" alt="Grammer checker" />
                  <p>Create grammar checking easy, precise and effective.</p>
                  <a href="#" className={styles.linkCtn}>
                      <span>Learn more </span>
                      <img src="./Arrow 1.png" alt="Arrow" />
                  </a>
                </div>
                <button className={styles.cardBtn}>Grammer Check</button>
              </div>

              <div>
                <div className={styles.card}>
                  <img src="./keyword-finder.png" alt="Grammer checker" />
                  <p>Find keywords easily, precisely and effectively.</p>
                  <a href="#" className={styles.linkCtn}>
                    <span>Learn more </span>
                    <img src="./Arrow 1.png" alt="Arrow" />
                  </a>
                </div>
                <button className={styles.cardBtn}>Keyword Finder</button>
              </div>

              <div>
                <div className={styles.card}>
                  <img src="./keyword-density-analyser.png" alt="Grammer checker" />
                  <p>Find keywords easily, precisely and effectively.</p>
                  <a href="#" className={styles.linkCtn}>
                    <span>Learn more </span>
                    <img src="./Arrow 1.png" alt="Arrow" />
                  </a>
                </div>
                <button className={styles.cardBtn}>Keyword Density Analyzer</button>
              </div>

            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
